"""Frame Navigator — walks visual frames with step-locked sync.

Replaces the segment-based DagNavigator for v2 lessons that have
pre-generated VisualFrame storyboards. The key difference: animations
NEVER auto-play. The teacher controls every step, ensuring perfect
sync between speech and visuals.
"""

import asyncio
import logging
from typing import AsyncGenerator

from app.agents.teacher import speech_gen
from app.agents.teacher.dialogue_state import DialogueState
from app.agents.teacher.models import (
    AnimationControlMessage,
    AskQuestionMessage,
    FrameBundleMessage,
    FrameChangeMessage,
    SeekStepMessage,
    SessionCompleteMessage,
    ShowFrameMessage,
    SpeakMessage,
    TeacherMessage,
    WaitMessage,
)
from app.services.audio_cache import SessionAudioCache

logger = logging.getLogger(__name__)


class FrameNavigator:
    """Navigates visual frames, yielding bundled lockstep messages.

    For each frame, sends ONE FrameBundleMessage containing all step audio.
    The frontend lockstep engine plays them in perfect sync (seek → audio →
    tween → repeat). Backend waits for `frame_done` from the frontend before
    advancing to the next frame.

    Audio is generated by `audio_cache` either ahead-of-time during the
    session-create prefetch task, or on-demand during _teach_frame as a
    fallback.
    """

    def __init__(
        self,
        frames: list[dict],
        animation_urls: dict[str, str],
        lesson_title: str,
        opening_hook: str,
        closing_summary: list[str],
        teaching_style: str,
        student_name: str,
        state: DialogueState,
        audio_cache: SessionAudioCache,
        frame_step_specs: dict[str, list[dict]],  # frame_id -> [{label, anim_time, text}]
    ):
        self.frames = frames
        self.animation_urls = animation_urls
        self.lesson_title = lesson_title
        self.opening_hook = opening_hook
        self.closing_summary = closing_summary
        self.teaching_style = teaching_style
        self.student_name = student_name
        self.state = state
        self.audio_cache = audio_cache
        self.frame_step_specs = frame_step_specs

        # Runtime state
        self.hand_raised: bool = False
        self.hand_raiser_name: str = ""
        self.pending_question: str = ""
        self.paused: bool = False
        self._student_response: str | None = None
        self._response_event = asyncio.Event()
        self._speech_done_event = asyncio.Event()
        self._speech_done_event.set()
        self._frame_done_event = asyncio.Event()
        self._frame_done_event.set()

    @property
    def total_frames(self) -> int:
        return len(self.frames)

    def acknowledge_speech(self) -> None:
        """Called when frontend finishes playing speech."""
        self._speech_done_event.set()

    def acknowledge_frame_done(self) -> None:
        """Called when frontend finishes playing the entire frame bundle."""
        self._frame_done_event.set()

    def receive_response(self, text: str) -> None:
        """Called when student responds to a question."""
        self._student_response = text
        self._response_event.set()

    def raise_hand(self, student_name: str) -> None:
        self.hand_raised = True
        self.hand_raiser_name = student_name

    def set_question(self, question: str) -> None:
        self.pending_question = question
        self._response_event.set()

    async def _wait_speech_done(self, timeout: float = 180) -> None:
        """Wait for frontend to signal speech_done."""
        self._speech_done_event.clear()
        try:
            await asyncio.wait_for(self._speech_done_event.wait(), timeout=timeout)
        except asyncio.TimeoutError:
            logger.warning("[FrameNav] speech_done timeout, proceeding")

    async def run(self) -> AsyncGenerator[TeacherMessage, None]:
        """Main teaching loop — yields bundled lockstep messages."""

        # Determine starting point
        start_idx = 0
        is_resuming = bool(
            self.state.current_frame_id and self.state.frames_completed
        )
        if is_resuming:
            for i, f in enumerate(self.frames):
                if f.get("frame_id") == self.state.current_frame_id:
                    start_idx = i
                    break

        # Pre-show the first frame BEFORE the opening speech so the screen
        # is never blank. The animation iframe loads while the opening plays.
        if self.frames and start_idx < len(self.frames):
            first = self.frames[start_idx]
            first_id = first.get("frame_id", f"f{start_idx:02d}")
            first_url = self.animation_urls.get(first_id, "")
            if first_url:
                yield ShowFrameMessage(frame_id=first_id, frame_url=first_url)
                yield AnimationControlMessage(action="pause")

        # Generate the opening (or welcome-back) speech as a single SpeakMessage.
        # The router synthesizes audio via Piper (~1-2s now, vs ~24s with Kokoro).
        if is_resuming:
            scores = self.state.get_score_summary()
            remaining = self.total_frames - len(self.state.frames_completed)
            welcome = await speech_gen.generate_welcome_back(
                student_name=self.student_name,
                lesson_title=self.lesson_title,
                last_segment=self.state.current_frame_id,
                segments_remaining=remaining,
                correct=scores.get("correct", 0),
                total=scores.get("total", 0),
                teaching_style=self.teaching_style,
            )
            yield SpeakMessage(text=welcome, speech_type="opening")
            self.state.add_dialogue("teacher", welcome)
        else:
            opening = await speech_gen.generate_opening(
                opening_hook=self.opening_hook or "Let's begin!",
                lesson_title=self.lesson_title,
                student_name=self.student_name,
                teaching_style=self.teaching_style,
            )
            yield SpeakMessage(text=opening, speech_type="opening")
            self.state.add_dialogue("teacher", opening)

        yield WaitMessage(seconds=1, reason="opening_pause")

        # Main frame loop — bundled lockstep
        for idx in range(start_idx, len(self.frames)):
            frame = self.frames[idx]
            frame_id = frame.get("frame_id", f"f{idx:02d}")

            # Handle pause
            while self.paused:
                await asyncio.sleep(1)

            self.state.start_frame(frame_id)

            async for msg in self._teach_frame(frame, frame_id, idx):
                yield msg

            # Handle interaction if present
            interaction = frame.get("interaction")
            if interaction:
                async for msg in self._handle_interaction(frame, interaction):
                    yield msg

            # Handle raised hands at frame boundaries
            if self.hand_raised:
                async for msg in self._handle_raised_hand(frame):
                    yield msg

            self.state.complete_frame(frame_id)

        # Lesson complete
        scores = self.state.get_score_summary()
        areas = self.state.get_areas_for_review()
        closing = await speech_gen.generate_closing(
            summary_points=self.closing_summary or [],
            scores=scores,
            areas_for_review=areas,
            teaching_style=self.teaching_style,
        )
        yield SpeakMessage(text=closing, speech_type="closing")
        self.state.add_dialogue("teacher", closing)

        total_time = sum(self.state.time_per_frame.values())
        summary = {
            "concepts_covered": [
                self._get_description(f)[:80]
                for f in self.frames
                if f.get("frame_id") in self.state.frames_completed
            ],
            "time_spent_minutes": round(total_time / 60, 1),
            "frames_completed": len(self.state.frames_completed),
            "questions_asked": scores.get("total", 0),
            "questions_correct": scores.get("correct", 0),
            "areas_for_review": areas,
        }
        yield SessionCompleteMessage(summary=summary)

    # ── Step-locked sync: seek → speak → wait → next step ──

    async def _teach_frame(
        self, frame: dict, frame_id: str, idx: int,
    ) -> AsyncGenerator[TeacherMessage, None]:
        """Send a single bundled FrameBundleMessage and wait for frame_done.

        The frontend lockstep engine handles all per-step playback.

        Speech source priority (highest first):
          1. frame.steps[].narration_spoken from the Opus storyboard
             (this is the 3b1b-quality script — use it verbatim)
          2. Groq fallback via generate_step_speeches (legacy frames)
        """
        # Step specs from animation HTML, populated by the router. If missing
        # (single-step frame or extraction failed), use a single 'main' step.
        step_specs = self.frame_step_specs.get(frame_id) or [
            {"label": "main", "anim_time": 0.0, "text": ""}
        ]
        labels_summary = [s.get("label", "?") for s in step_specs]
        print(
            f"[FrameNav] {frame_id} step_specs: {len(step_specs)} steps, "
            f"labels={labels_summary}",
            flush=True,
        )

        # ── Source 1: Opus narration_spoken from the storyboard ──
        # If the planner emitted steps with narration, use them verbatim.
        # We match by label so the order/count of HTML labels and storyboard
        # steps don't have to be identical.
        opus_step_text = _build_opus_step_lookup(frame)
        if opus_step_text:
            applied = 0
            new_specs: list[dict] = []
            for spec in step_specs:
                label = spec.get("label", "")
                opus_text = opus_step_text.get(label, "")
                if opus_text:
                    applied += 1
                    new_specs.append({
                        **spec,
                        "text": speech_gen.sanitize_for_tts(opus_text),
                    })
                else:
                    new_specs.append(spec)
            step_specs = new_specs
            print(
                f"[FrameNav] {frame_id} matched {applied}/{len(step_specs)} "
                f"steps to Opus narration",
                flush=True,
            )
        else:
            print(f"[FrameNav] {frame_id} no Opus narration_spoken found", flush=True)

        # ── Source 2: Groq generation when narration is missing or too short ──
        # Quality gate: if Opus narration averages < 50 chars per step, it's
        # just a brief caption ("Roll a single die."), not teaching content.
        # In that case, use Groq to generate proper 3b1b-style narration,
        # passing the short Opus text as step descriptions for context.
        texts_with_content = [s.get("text", "") for s in step_specs if s.get("text")]
        avg_text_len = (
            sum(len(t) for t in texts_with_content) / len(texts_with_content)
            if texts_with_content else 0
        )
        narration_too_short = texts_with_content and avg_text_len < 50

        cached = await self.audio_cache.get(frame_id)
        needs_speech_gen = (
            cached is None
            or not cached.steps
            or all(not s.text for s in cached.steps)
        ) and not any(s.get("text") for s in step_specs)

        if narration_too_short:
            print(
                f"[FrameNav] {frame_id} Opus narration too short "
                f"(avg={avg_text_len:.0f}ch), using Groq to expand",
                flush=True,
            )
            needs_speech_gen = True

        if needs_speech_gen:
            if not narration_too_short:
                print(
                    f"[FrameNav] {frame_id} no narration, falling back to Groq",
                    flush=True,
                )
            try:
                # Build enhanced labels: "single-die — Roll a single die."
                # so Groq has the brief description as context
                enhanced_labels = []
                opus_narrations = []
                for s in step_specs:
                    label = s.get("label", "")
                    text = s.get("text", "")
                    if text:
                        enhanced_labels.append(f"{label} — {text}")
                        opus_narrations.append(text)
                    else:
                        enhanced_labels.append(label)
                        opus_narrations.append("")

                speeches = await speech_gen.generate_step_speeches(
                    frame=frame,
                    step_labels=enhanced_labels,
                    student_name=self.student_name,
                    teaching_style=self.teaching_style,
                )
                step_specs = [
                    {**spec, "text": speeches[i] if i < len(speeches) else ""}
                    for i, spec in enumerate(step_specs)
                ]
            except Exception as e:
                print(f"[FrameNav] {frame_id} inline speech gen failed: {e}", flush=True)

        # Trigger prefetch if not already started — no-op if cached.
        # Awaiting this guarantees audio is ready before we yield the bundle.
        audio = await self.audio_cache.prefetch(frame_id, step_specs)

        # Build the steps payload (audio + duration from cache, fall back to spec text)
        if audio.error:
            print(
                f"[FrameNav] {frame_id} audio cache error '{audio.error}', sending text-only",
                flush=True,
            )
            steps_payload = [
                {
                    "label": s.get("label", ""),
                    "anim_time": s.get("anim_time", 0.0),
                    "text": s.get("text", ""),
                    "audio_b64": "",
                    "duration_s": 0.0,
                }
                for s in step_specs
            ]
        else:
            steps_payload = [
                {
                    "label": s.label,
                    "anim_time": s.anim_time,
                    "text": s.text,
                    "audio_b64": s.audio_b64,
                    "duration_s": s.duration_s,
                }
                for s in audio.steps
            ]

        # Track dialogue history (concat all step texts for context)
        full_text = " ".join(s["text"] for s in steps_payload if s["text"])
        if full_text:
            self.state.add_dialogue("teacher", full_text)
            self.state.record_opening_phrase(full_text)

        progress = (idx / self.total_frames) * 100
        url = self.animation_urls.get(frame_id, "")

        # Log step payload details for diagnostics
        step_summary = []
        for i, s in enumerate(steps_payload):
            has_audio = bool(s.get("audio_b64"))
            dur = s.get("duration_s", 0)
            txt_len = len(s.get("text", ""))
            step_summary.append(
                f"  step[{i}] label={s.get('label', '?')} "
                f"audio={'yes' if has_audio else 'NO'} dur={dur:.1f}s txt={txt_len}ch"
            )
        print(
            f"[FrameNav] {frame_id} SENDING bundle: "
            f"{len(steps_payload)} steps, url={'yes' if url else 'EMPTY'}\n"
            + "\n".join(step_summary),
            flush=True,
        )

        yield FrameBundleMessage(
            frame_id=frame_id,
            frame_url=url,
            frame_index=idx,
            total_frames=self.total_frames,
            progress_pct=round(progress, 1),
            frame_title=str(frame.get("title", "")) or self._get_description(frame)[:80],
            fallback_description=self._get_description(frame)[:200],
            steps=steps_payload,
        )

        # Wait for the frontend lockstep engine to finish all steps.
        # Timeout: audio time + animation transition time + margin.
        # The frontend timeout per transition = anim_time_diff + 4s margin,
        # so we sum the actual anim_time gaps (from step specs) + 4s each.
        self._frame_done_event.clear()
        total_audio = sum(s["duration_s"] for s in steps_payload)
        # Sum actual transition durations between consecutive steps
        anim_times = [s.get("anim_time", 0.0) for s in steps_payload]
        transition_sum = sum(
            max(anim_times[i + 1] - anim_times[i], 2.0)
            for i in range(len(anim_times) - 1)
        ) if len(anim_times) > 1 else 0.0
        animate_budget = transition_sum + len(steps_payload) * 4.0  # 4s margin each
        timeout = max(90.0, total_audio + animate_budget + 20.0)
        print(
            f"[FrameNav] {frame_id} WAITING for frame_done "
            f"(audio={total_audio:.1f}s, timeout={timeout:.0f}s)",
            flush=True,
        )
        try:
            await asyncio.wait_for(self._frame_done_event.wait(), timeout=timeout)
            print(f"[FrameNav] {frame_id} frame_done RECEIVED — advancing", flush=True)
        except asyncio.TimeoutError:
            print(
                f"[FrameNav] {frame_id} frame_done TIMEOUT ({timeout:.0f}s) — "
                f"forcing advance",
                flush=True,
            )

    # ── Interaction handling ──

    async def _handle_interaction(
        self, frame: dict, interaction: dict,
    ) -> AsyncGenerator[TeacherMessage, None]:
        """Handle a frame's interaction (question, prediction, etc.)."""
        frame_id = frame.get("frame_id", "")
        question = interaction.get("prompt", "")
        expected = interaction.get("expected_response", "")
        hints = interaction.get("hints", [])
        max_attempts = 3

        # Question intro
        intro = await speech_gen.generate_question_intro(
            question=question,
            question_type=interaction.get("interaction_type", "question"),
            teaching_style=self.teaching_style,
        )
        yield SpeakMessage(text=intro, speech_type="question")
        self.state.add_dialogue("teacher", intro)

        # Send question to frontend
        yield AskQuestionMessage(
            question=question,
            question_type=interaction.get("interaction_type", "question"),
            hints=hints,
            segment_id=frame_id,
        )

        yield WaitMessage(seconds=4, reason="thinking_time")

        # Wait for response with retry loop
        hints_given = 0
        for attempt in range(1, max_attempts + 1):
            self._response_event.clear()
            self._student_response = None

            try:
                await asyncio.wait_for(self._response_event.wait(), timeout=60)
            except asyncio.TimeoutError:
                # Student didn't respond
                if attempt < max_attempts and hints_given < len(hints):
                    hint_speech = f"Here's a hint: {hints[hints_given]}"
                    yield SpeakMessage(text=hint_speech, speech_type="feedback")
                    hints_given += 1
                    yield WaitMessage(seconds=3, reason="hint_pause")
                    continue
                else:
                    self.state.record_score(frame_id, "confused", attempt, hints_given, question)
                    timeout_speech = "No worries! Let me explain the answer."
                    if expected:
                        timeout_speech += f" The key idea is: {expected}"
                    yield SpeakMessage(text=speech_gen.sanitize_for_tts(timeout_speech), speech_type="feedback")
                    self.state.add_dialogue("teacher", timeout_speech)
                    return

            answer = self._student_response or ""
            self.state.add_dialogue("student", answer)

            # Evaluate
            evaluation = await speech_gen.evaluate_response(
                question=question,
                expected_answer=expected or "Any thoughtful response",
                student_answer=answer,
                hints_given=hints_given,
                attempt=attempt,
            )

            # Generate feedback
            remaining_hints = hints[hints_given:]
            feedback = await speech_gen.generate_feedback(
                question=question,
                student_answer=answer,
                verdict=evaluation.verdict,
                explanation=evaluation.explanation,
                attempt=attempt,
                remaining_hints=remaining_hints,
                teaching_style=self.teaching_style,
            )
            yield SpeakMessage(text=feedback, speech_type="feedback")
            self.state.add_dialogue("teacher", feedback)

            if evaluation.verdict == "correct":
                self.state.record_score(frame_id, "correct", attempt, hints_given, question)
                return

            if evaluation.verdict == "confused":
                self.state.record_score(frame_id, "confused", attempt, hints_given, question)
                return

            # Wrong — give hint if available
            if hints_given < len(hints):
                hints_given += 1

            if attempt >= max_attempts:
                self.state.record_score(frame_id, "wrong", attempt, hints_given, question)
                return

            yield WaitMessage(seconds=3, reason="retry_thinking_time")

    # ── Raised hand handling ──

    async def _handle_raised_hand(
        self, current_frame: dict,
    ) -> AsyncGenerator[TeacherMessage, None]:
        """Handle a student's raised hand."""
        name = self.hand_raiser_name or self.student_name
        self.hand_raised = False

        ack = f"I see you have a question, {name}. Go ahead!"
        yield SpeakMessage(text=ack, speech_type="response")
        self.state.add_dialogue("teacher", ack)

        self._response_event.clear()
        self._student_response = None

        try:
            await asyncio.wait_for(self._response_event.wait(), timeout=30)
        except asyncio.TimeoutError:
            yield SpeakMessage(
                text="No worries, you can ask anytime. Let's continue.",
                speech_type="response",
            )
            return

        question = self.pending_question or self._student_response or ""
        self.pending_question = ""
        self.state.add_dialogue("student", question)

        description = self._get_description(current_frame)
        response = await speech_gen.handle_student_question(
            student_question=question,
            current_topic=description[:100],
            segment_key_points=[description[:200]],
            recent_context=self.state.get_recent_context(),
            teaching_style=self.teaching_style,
        )
        yield SpeakMessage(text=response, speech_type="response")
        self.state.add_dialogue("teacher", response)

        yield WaitMessage(seconds=2, reason="question_answered")

    # ── Helpers ──

    def _get_description(self, frame: dict) -> str:
        """Get the visual description from a frame."""
        vspec = frame.get("visual_spec", {})
        desc = vspec.get("description", "")
        if not desc:
            desc = str(vspec)
        return desc


def _build_opus_step_lookup(frame: dict) -> dict[str, str]:
    """Build a {label: narration_spoken} map from a v4 frame's steps list.

    The Course Planner v4 prompt requires every frame.steps[] entry to have
    `label` + `narration_spoken`. We trust that and key by label so the
    HTML-extracted GSAP labels (which drive sync) can pull the right text.
    Missing labels just fall through to the Groq fallback in _teach_frame.
    """
    lookup: dict[str, str] = {}
    for s in frame.get("steps") or []:
        if not isinstance(s, dict):
            continue
        label = (s.get("label") or "").strip()
        text = (s.get("narration_spoken") or s.get("narration") or "").strip()
        if label and text:
            lookup[label] = text
    return lookup
