"""HTML template for visual frames — Claude fills in the animation code only."""

FRAME_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-python.min.js"></script>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    background: #0d1117; color: #c9d1d9;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    width: 100vw; height: 100vh; overflow: hidden;
    display: flex; align-items: center; justify-content: center;
}}
#canvas-container {{
    width: 100%; height: 100%; position: relative;
}}
svg {{ width: 100%; height: 100%; }}
canvas {{ width: 100%; height: 100%; }}
.katex {{ font-size: 1.4em; }}
</style>
</head>
<body>
<div id="canvas-container">
{content_html}
</div>
<script>
// ── GSAP Master Timeline ──
const tl = gsap.timeline({{ paused: true }});

// ── Animation API (available immediately) ──
window.animationAPI = {{
    timeline: tl,
    seekToStep(label) {{ tl.seek(label); tl.pause(); }},
    play() {{ tl.play(); }},
    pause() {{ tl.pause(); }},
    getSteps() {{ return Object.keys(tl.labels); }},
    getCurrentStep() {{
        const t = tl.time();
        let current = '';
        for (const [name, time] of Object.entries(tl.labels)) {{
            if (time <= t) current = name;
        }}
        return current;
    }},
    onStepChange(cb) {{ this._cb = cb; }},
    _cb: null,
}};

// ── Step change notifier ──
let _lastStep = '';
function _notifyStepChange() {{
    const s = window.animationAPI.getCurrentStep();
    if (s !== _lastStep) {{
        _lastStep = s;
        if (window.animationAPI._cb) window.animationAPI._cb(s);
        window.parent.postMessage({{ event: 'stepChanged', label: s }}, '*');
    }}
    requestAnimationFrame(_notifyStepChange);
}}
_notifyStepChange();

// ── Listen for parent commands ──
window.addEventListener('message', (e) => {{
    const {{ action, label }} = e.data || {{}};
    if (action === 'seekToStep') window.animationAPI.seekToStep(label);
    else if (action === 'play') window.animationAPI.play();
    else if (action === 'pause') window.animationAPI.pause();
}});

// ══════════════════════════════════════════════════════════
// ── ANIMATION CODE (generated by Claude) ──
// ══════════════════════════════════════════════════════════
{animation_js}

// ── Auto-play after setup ──
tl.play();
</script>
</body>
</html>
"""
