"use client";

import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { useUser } from "@/hooks/use-user";
import { MaterialIcon } from "@/components/shared/material-icon";

interface CourseRow {
  goal_id: string;
  goal_title: string;
  total_modules: number;
  total_lessons: number;
  lessons_ready: number;
  is_complete: boolean;
  updated_at: string;
}

export default function CoursesPage() {
  const { user, loading: userLoading } = useUser();
  const [courses, setCourses] = useState<CourseRow[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    if (!user) return;
    const sb = createClient();
    const { data, error } = await sb
      .from("course_plans")
      .select(
        `goal_id, total_modules, total_lessons, generation_metadata, updated_at,
         learning_goals!inner(title)`
      )
      .eq("user_id", user.id)
      .order("updated_at", { ascending: false });

    if (error) {
      console.error("[Courses] fetch error:", error);
      setCourses([]);
      setLoading(false);
      return;
    }

    const rows: CourseRow[] = (data ?? []).map((c) => {
      const meta = (c.generation_metadata ?? {}) as {
        lessons_ready?: number;
        is_complete?: boolean;
      };
      const goal = c.learning_goals as unknown as { title: string };
      return {
        goal_id: c.goal_id as string,
        goal_title: goal?.title ?? "Untitled goal",
        total_modules: (c.total_modules as number) ?? 0,
        total_lessons: (c.total_lessons as number) ?? 0,
        lessons_ready: meta.lessons_ready ?? 0,
        is_complete: meta.is_complete ?? false,
        updated_at: c.updated_at as string,
      };
    });

    setCourses(rows);
    setLoading(false);
  }, [user]);

  useEffect(() => {
    if (userLoading) return;
    if (!user) {
      setLoading(false);
      return;
    }

    load();

    const sb = createClient();
    const channel = sb
      .channel(`courses-${user.id}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "course_plans",
          filter: `user_id=eq.${user.id}`,
        },
        () => {
          load();
        }
      )
      .subscribe();

    return () => {
      sb.removeChannel(channel);
    };
  }, [user, userLoading, load]);

  if (loading || userLoading) {
    return (
      <div className="p-8 max-w-7xl mx-auto w-full animate-pulse">
        <div className="h-8 w-48 bg-muted rounded mb-8" />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-40 bg-muted rounded-xl" />
          ))}
        </div>
      </div>
    );
  }

  if (courses.length === 0) {
    return (
      <div className="p-4 md:p-8 max-w-7xl mx-auto w-full">
        <h1 className="text-3xl font-black tracking-tight mb-2">My Courses</h1>
        <p className="text-slate-500 dark:text-slate-400 mb-12">
          Your AI-generated courses will appear here.
        </p>
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <div className="size-16 rounded-2xl bg-primary/10 text-primary flex items-center justify-center mb-6">
            <MaterialIcon name="auto_stories" className="text-3xl" />
          </div>
          <h3 className="text-xl font-bold mb-2">No courses yet</h3>
          <p className="text-sm text-slate-500 max-w-sm mb-6">
            Create a learning goal and the AI agents will build a full course
            for you.
          </p>
          <Link
            href="/onboarding/goal"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-primary text-white text-sm font-bold hover:bg-primary/90 transition-colors"
          >
            Create a Goal
            <MaterialIcon name="arrow_forward" className="text-base" />
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto w-full">
      <h1 className="text-3xl font-black tracking-tight mb-2">My Courses</h1>
      <p className="text-slate-500 dark:text-slate-400 mb-12">
        {courses.length} course{courses.length === 1 ? "" : "s"} generated by
        your AI agents.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {courses.map((c) => {
          const pct =
            c.total_lessons > 0
              ? Math.round((100 * c.lessons_ready) / c.total_lessons)
              : 0;
          return (
            <Link
              key={c.goal_id}
              href={`/courses/${c.goal_id}`}
              className="group flex flex-col p-6 rounded-xl border border-primary/10 bg-white dark:bg-slate-900 shadow-sm hover:border-primary/30 hover:shadow-md transition-all"
            >
              <div className="flex items-center justify-between mb-4">
                <div className="size-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
                  <MaterialIcon name="menu_book" className="text-xl" />
                </div>
                {c.is_complete ? (
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-emerald-500/10 text-emerald-500">
                    Ready
                  </span>
                ) : (
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-amber-500/10 text-amber-500">
                    Building
                  </span>
                )}
              </div>
              <h3 className="font-bold text-lg mb-2 line-clamp-2 group-hover:text-primary transition-colors">
                {c.goal_title}
              </h3>
              <p className="text-sm text-slate-500 mb-4">
                {c.total_modules} modules · {c.total_lessons} lessons
              </p>
              <div className="mt-auto">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">
                    {c.lessons_ready}/{c.total_lessons} lessons ready
                  </span>
                  <span className="text-xs font-mono font-bold text-primary">
                    {pct}%
                  </span>
                </div>
                <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-primary rounded-full transition-all"
                    style={{ width: `${pct}%` }}
                  />
                </div>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
